### ISSUE TITLE
Index.html not found

### ISSUE THREAD

**Issue by legojack100** [Forceh91/retro-env-can-weather-chan#150]
After running backend.js, the program runs as intended.
However, when accessing the website link provided, the console displays this error:

Error: ENOENT: no such file or directory, stat '/home/pi/Downloads/retro-env-can-weather-chan-master/dist/index.html'

I have found the index file in a folder named "public", however when I rename the folder to dist the index.html file is blank, with nothing on the webpage when opened.
Is there something I have missed?

**Comment by lokilust** [comment]
i having the same problem ?

**Comment by Forceh91** [comment]
> i was having the same problem until i used $ yarn build everything started to work after that.

Yep this is the solution. I've updated the README to reflect this.
