### ISSUE TITLE
temporarily unavailable

### ISSUE THREAD

**Issue by lokilust** [Forceh91/retro-env-can-weather-chan#152]
When i go to 192.168.2.14:8600 from a different computer i get 
![Screenshot from 2022-01-16 16-09-29](https://user-images.githubusercontent.com/4175095/149678275-a4030379-3a56-48e7-a467-52c9f7bd8c26.png)

**Comment by Forceh91** [comment]
This is most likely a CORS issue. I'll have to investigate the best way around this. I suspect it's an issue with how I setup the endpoints in the `backend.js`

**Comment by lokilust** [comment]
I know you've been busy but have you had a chance to look at the see what's going on?

**Comment by Forceh91** [comment]
I've just taken a look at this and from a very quick test I think you should be able to modify `backend.js` to solve this issue.

You'll find some code that looks like this on **Line 13** of `backend.js`:

```
const corsOptions = {
  origin: "http://localhost:8080",
  optionsSuccessStatus: 200,
};
```

If you change it to this (making sure the correct IP is inserted), then it'll hopefully let you access the channel.

```
const corsOptions = {
  origin: ["http://localhost:8080", "http://192.168.2.14:8600"],
  optionsSuccessStatus: 200,
};
```

I only have the one PC on this network that I can test this on so let me know it goes!

**Comment by lokilust** [comment]
That works perfect.

Thanks

**Comment by lokilust** [comment]
Crap i just did it from a different computer on my network and it did not work

**Comment by Forceh91** [comment]
Is the computer the channel is running from on a different IP or something?

**Comment by lokilust** [comment]
No same network but i did get it to work after i edited the /dist/js/app.123456789.js file.
Changed all
`this.$http.get("//localhost:8600/api/weather`
to
`this.$http.get("//192.168.2.14:8600/api/weather`
I think if i added `["http://localhost:8080", "http://192.168.2.14:8600"]` before i `yarn build`

There has to be a different way to do it ?

**Comment by Forceh91** [comment]
Oh right.. No changing the stuff in `backend.js` won't effect what is referenced in the `App.vue` file. This would need a larger change. I forgot I hard-coded it to be localhost requests.

**Comment by lokilust** [comment]
Okay 
It is a shame that in the setup.js before you set your weather location you can set localhost or a domain.

**Comment by lokilust** [comment]
Should i start to rebuild it again and see if i have the same issue ?

**Comment by Forceh91** [comment]
> Should i start to rebuild it again and see if i have the same issue ?

You'll have to checkout the other branch that this is on `remove-localhost-hardcode` and see if that works for you. It should do, I tested it using both `localhost` and a network IP.

**Comment by Forceh91** [comment]
@lokilust Try this version out and let me know how it is

[v0.10.1.zip](https://github.com/Forceh91/retro-env-can-weather-chan/files/8147386/v0.10.1.zip)

**Comment by lokilust** [comment]
That works perfectly. 
thanks.

**Comment by lokilust** [comment]
Now I'm trying to view it online via domain.com. 
I've read a bunch of how to do such as https://medium.com/@chamiperera95/how-to-run-node-js-server-and-apache-server-together-ee225ece6a44
Do you have any suggestions ?
