### ISSUE TITLE
Playlist stops running after a while

### ISSUE THREAD

**Issue by Forceh91** [Forceh91/retro-env-can-weather-chan#2]
I haven't been able to figure out what the cause of this but if you leave the channel running for long enough the audio will just stop playing completely. I don't know if this is due to all of the audio tracks having been played once and Firefox not wanting to loop the audio? I do destroy the `audio` element each track change though so I don't think it's that.

**Comment by lokilust** [comment]
Can you add a online radio station [https://www.iheartradio.ca/](url) to play ?
