### ISSUE TITLE
Initial set up fails to compile on build

### ISSUE THREAD

**Issue by fatwreck** [Forceh91/retro-env-can-weather-chan#306]
This project looks great but I can't get it to run.

- On M1 Mac (Monterey)
- Node 14.20.0
- npm 8.19.1
_______________________

- running yarn install from the repo directory
- then yarn build for fun and build files
- then shut that down and yarn serve

Resulting error:
<img width="843" alt="Screen Shot 2022-10-10 at 10 13 35 AM" src="https://user-images.githubusercontent.com/12806853/194910445-308dfe85-0921-46a0-b399-6bcbe4567b78.png">

I'm not great as this stuff, but the Vue-jest dependency seems to be doing something the build doesn't like

`warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has incorrect peer dependency "vue@^2.x".`
`warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has unmet peer dependency "vue-template-compiler@^2.x".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "@babel/core@7.x".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "babel-jest@>= 24 < 27".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "jest@>= 24 < 27 ".`

Any ideas?
Thanks!

**Comment by fatwreck** [comment]
I really don't know why, but it's working now.

I pulled master which didn't have any `package.json` updates just edits and bug fixes.

I deleted the `node_modules` folder just like I do every time and ran `yarn install` then `yarn serve` and on the 5? 6? time around it decided to work.

The `yarn.lock` file contained this modification in the end
` csstype@^2.6.8:`
**Removed**
`-  version "2.6.17"`
`-  resolved "https://registry.yarnpkg.com/csstype/-/csstype-2.6.17.tgz#4cf30eb87e1d1a005d8b6510f95292413f6a1c0e"`
`-  integrity sha512-u1wmTI1jJGzCJzWndZo8mk4wnPTZd1eOIYTYvuEyOQGfmDl3TrabCCfKnOC86FZwW/9djqTl933UF/cS425i9A==`
**Added**
`+  version "2.6.21"`
`+  resolved "https://registry.yarnpkg.com/csstype/-/csstype-2.6.21.tgz#2efb85b7cc55c80017c66a5ad7cbd931fda3a90e"`
`+  integrity sha512-Z1PhmomIfypOpoMjRQB70jfvy/wxT50qW08YXO5lMIJkrdq4yOTR+AW7FqutScmB9NkLwxo+jU+kZLbofZZq/w==`

**Yarn Install Warnings** - Didn't change
`warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has incorrect peer dependency "vue@^2.x".`
`warning "@vue/cli-plugin-unit-jest > vue-jest@3.0.7" has unmet peer dependency "vue-template-compiler@^2.x".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "@babel/core@7.x".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "babel-jest@>= 24 < 27".`
`warning " > vue-jest@5.0.0-alpha.10" has unmet peer dependency "jest@>= 24 < 27 ".`

I don't know why, but that's sometimes the nature of this stuff.

I'm around if you wanted to dig in, but otherwise safe to close ticket.

**Comment by Forceh91** [comment]
Sorry, only just seen this. I'll do a fresh `node_modules` myself and `yarn install` and see what happens. One of the package updates might have caused some weird sub-dependency update perhaps?

**Comment by Forceh91** [comment]
@fatwreck As you mentioned clearing the `node_modules` and doing a fresh `yarn install` on the latest `master` seems like everything should be good. Let me know if you run into this again and/or find a good way to reproduce this!

**Comment by fatwreck** [comment]
@Forceh91 Thanks for taking a look. It's been building/serving reliably now. Pulled latest and still good.

However, I'm unable to access the config page but it could be me. The README often references `http://localhost:8600/`, but in my understanding, the typical default is `http://localhost:8080/`, so I'm not sure if this is a Vue quark or the package.json should set port to 8600 to get everyone on the same page. If it's the latter, I think changing line 6 on the `package.json` to `vue-cli-service serve --port 8600`

My local is using `http://localhost:8080/` but hitting `http://localhost:8080/#/config/` gets stuck on `Fetching config... please wait.` with a console error `http://localhost:8080/api/init 404 (Not Found)`

The `req` argument in the `startBackend` function in the `backend.js` file is empty/unused. Maybe it's populated from the missing(?) `api/init` file? Sounds like a file, but an init file would be unusual. idk :)

One last thing, do you recommend running the `master` branch or the `release/v1.x.x`? Running a release sounds more of a sure thing to me.

Thanks

**Comment by Forceh91** [comment]
I'm just about to merge the `release/v1.1.3` to the `master` branch, I recommend using `master` or you can go off the latest tag which will be the last stable release.

I'll open a new issue for the config page not loading, I think because you're running this via `yarn serve` as opposed to `yarn build` it's getting confused with port numbers etc.
