### ISSUE TITLE
Windchill Page - Coming up seasonally

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#337]
Is it possible to have the windchill page stay as a regular part of the cycle versus only coming up when there is a windchill? 
This way, it would function more like a seasonal page - with it always there from November through April, or so.

**Comment by Forceh91** [comment]
Hmm we'd need a separate windchill season calculating for that but it is doable. Right now it has knowledge of the summer/winter season from the precip data.

Would this be Nov 1st - Apr 30 for the windchill?

**Comment by wpgne** [comment]
Yeah, that would be a reasonable timeframe. The original channel had that info page there all the time during the winter season - not just when windchill was reported.
