### ISSUE TITLE
Light Freezing Drizzle Condition Abbreviation

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#369]
Another winter condition that needs abbreviation to fit in the 13 spaces available
LGT FRZG DRZL would be the appropriate abbreviation to set it to
![ECW - Light Freezing D](https://user-images.githubusercontent.com/117599578/206790624-aa0f7653-03e8-4761-9fc6-c034ee4c2f38.png)

**Comment by Forceh91** [comment]
@wpgne The current condition for Winnipeg (forecast/records) allows for 16 characters right now, is that correct?

**Comment by wpgne** [comment]
I believe it should be the same as all the other locations - to simplify and standardize what the viewer sees - so 13 characters or less, even for Winnipeg ie: the "main" city

**Comment by wpgne** [comment]
Looks like this condition is showing up in the abbreviated form now for both the main city and on the other city page(s)...
![ECW - Lgt Frzg Drzl-Main City](https://user-images.githubusercontent.com/117599578/206877200-a2889bb7-543f-4ab7-93d1-5d159051f7d9.png)
![ECW - Lgt Frzg Drzl-Regional Obs](https://user-images.githubusercontent.com/117599578/206877201-1cd68de5-8c86-4f2c-8b40-3d7580c9175c.png)
