### ISSUE TITLE
Standardization of Weather Conditions

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#370]
Need to go through the conditions used for city observations and standardize how they display
For example, some locations say LGT RAIN while another says LIGHT RAIN, even on the same page

Is this defined per location or is there a lookup table to check them all simultaneously?

Whenever possible, only abbreviate if 13 spaces isn't enough
In this example, LGT DRIZZLE could say LIGHT DRIZZLE
![ECW - Lgt Drizzle](https://user-images.githubusercontent.com/117599578/206791653-52f9a30f-d715-4a58-96e7-a383d6fc1de8.png)

**Comment by Forceh91** [comment]
Ah yeah for these ones it's because the weather is reporting as "Light Drizzle and [something]". I'm not sure why it's truncating so harshly after ditching the "and [something]". Did have a look a while back but couldn't figure out why.

**Comment by wpgne** [comment]
Ah, ok - good to know there's something more behind why it's doing that. It's tricky when there are multiple sky/weather values. In the case you mentioned, best for it to just say Light Drizzle and drop the Fog/Mist.

**Comment by Forceh91** [comment]
Reopening this as I didn't fully solve it. The #374 feature should improve on this (and actually solve it this time)

**Comment by wpgne** [comment]
OK, good to know you're still working on this as I was seeing things like Lgt Snow coming up.

**Comment by Forceh91** [comment]
Closed as of v1.5.0
