### ISSUE TITLE
One Location On U.S. Observations Page

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#372]
Saw this happen about an hour ago:
![ECW - Only One Location Showing](https://user-images.githubusercontent.com/117599578/206876974-353740d8-88e5-423d-87ad-02e6e8b97972.png)

I'm guessing there was some kind of issue on the API side. However, let's recall the rule for these pages: if there are less than 2 locations to display at a given time, the page should be skipped until more of them become available.

**Comment by Forceh91** [comment]
Fixed with #381
