### ISSUE TITLE
City Observations Mixing Between Regions

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#377]
As the API/update issues have illustrated today, the list of Canadian city observations are mixing with other regions when only a few are available.
The Manitoba/NW Ontario, Western Canada, & Eastern Canada pages (as well as the U.S. ones) were always separate from each other.
Need to separate them into distinct pages.
![ECW - City Obs Not on Separate Pages](https://user-images.githubusercontent.com/117599578/208325054-5477077a-6667-4f66-8e45-c7efef1b7fc4.png)

**Comment by Forceh91** [comment]
Fixed with #381
