### ISSUE TITLE
Warning/Watch/Advisory/Statement Page View Duration

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#400]
The view duration for this page is longer than all others and should ideally be set to the standard 14 second period the original channel had for all pages. This is especially true now that the discussion information displayed has been cut down to the first sentence or two.

**Comment by Forceh91** [comment]
Oh yeah I keep meaning to look into that. I think for some reason the extreme cold warning has been picked up twice
