### ISSUE TITLE
Warning/Watch/Advisories/Statement Page(s)

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#496]
Two things to configure for these page(s):
1. Priority order - First: Warnings - Second: Watches - Third: Advisories - Fourth: Statements
2. Title Flashing - Warnings & Watches: Yes - Advisories & Statements: No

**Comment by Forceh91** [comment]
One idea I had for the priority order of the warnings etc. was to use the info we get in the CAP files.

Sort by **severity**, and then by **urgency** (higher numbers coming first):

```
export const SEVERITY_VALUES = {
  UNKNOWN: 0,
  MINOR: 1,
  MODERATE: 2,
  SEVERE: 3,
  EXTREME: 4,
};

export const URGENCY_VALUES = {
  UNKNOWN: 0,
  PAST: 1,
  FUTURE: 2,
  EXPECTED: 3,
  IMMEDIATE: 4,
};
```

For yesterday's situation this would have produced the following order:

1. Severe Thunderstorm Watch (SEVERE, IMMEDIATE)
2. Heat Warning (SEVERE, FUTURE)

**Comment by wpgne** [comment]
Yes, that would be a prudent way to look at and prioritise it as well.

**Comment by Forceh91** [comment]
Interesting that the **Severe Thunderstorm Warning** has come across as less severe than the **Heat Warning**:

```
        <urgency>Immediate</urgency>
        <severity>Moderate</severity>
```

**Comment by wpgne** [comment]
You might need to manually order the warning types, to ensure they're displayed appropriately. It really should be a Heat Advisory, not a warning, but that's ECCC's doing.

**Comment by Forceh91** [comment]
Yeah we're kind of at  the mercy of ECCC but apart from that this seems to be working well, including the work for #495

**Comment by wpgne** [comment]
Yeah, saw it come up today. My only suggestion would be to make the text left aligned, like the original.

**Comment by Forceh91** [comment]
Oh it was left aligned? Will get it fixed.
