### ISSUE TITLE
how to put text on info screen?

### ISSUE THREAD

**Issue by TigerIS12024** [Forceh91/retro-env-can-weather-chan#817]
Up and running, I wonder how to put text on info screen

**Comment by Forceh91** [comment]
The info screen? Are you referring to the city stats screen with precip data and hot/cold spots?

**Comment by TigerIS12024** [comment]
No,  The info screen, which is the custom text screens written by the User.

**Comment by Forceh91** [comment]
That hasn't been implemented in v2
