### ISSUE TITLE
Inaccurate Sunrise/Sunset Times

### ISSUE THREAD

**Issue by wpgne** [Forceh91/retro-env-can-weather-chan#852]
The Sunrise/Sunset times for the Winnipeg streams have yet to update for several days, and are no longer accurate.

**Comment by Forceh91** [comment]
That would be an API issue or ECCC issue. They seem to be accurate to what's on [here](https://weather.gc.ca/en/location/index.html?coords=49.895,-97.135), unless it fixed itself?

**Comment by wpgne** [comment]
Ah, ok.
Looks like it fixed itself at the 14:00 reload today, as it was stuck on 7:33 AM / 7:01 PM for several days, then all of a sudden changed to the correct values of 7:55 AM / 6:32 PM. 
Will wait and see if it keeps pace for tomorrow.

**Comment by Forceh91** [comment]
Looked into this a bit more and for some reason the date the API is giving for sunrise/set is back in October so its throwing off whether it's on daylight savings or not..

**Comment by Forceh91** [comment]
I got a response from ECCC on this:

> Hi Matt,
> 
> Thanks a lot for your interest in our data and services.
> 
> I confirm the that this issue has already been identified and will be fixed through the next release on December 11th.

Fingers crossed!

**Comment by wpgne** [comment]
> I got a response from ECCC on this:
> 
> > Hi Matt,
> > Thanks a lot for your interest in our data and services.
> > I confirm the that this issue has already been identified and will be fixed through the next release on December 11th.
> 
> Fingers crossed!

Ah, cool. You reached out to them. Good to know they were aware of it and will implement a fix.

**Comment by Forceh91** [comment]
Confirmed that ECCC has deployed the fix for this now!
